language: c

notifications:
  email:
    - ddpbsd@gmail.com

env:
- DB=mysql OSSEC_TYPE=server GEOIP=yes
- DB=mysql OSSEC_TYPE=server GEOIP=no
- DB=pgsql OSSEC_TYPE=server GEOIP=yes
- DB=pgsql OSSEC_TYPE=server GEOIP=no
- DB=none OSSEC_TYPE=server GEOIP=yes
- DB=none OSSEC_TYPE=server GEOIP=no
- DB=none OSSEC_TYPE=server PRELUDE=yes ZEROMQ=yes
- DB=none OSSEC_TYPE=server ZLIB_SYSTEM=yes LUA_ENABLE=no
- DB=none OSSEC_TYPE=server USE_SQLITE=yes USE_LIBSODIUM=yes
- DB=none OSSEC_TYPE=local GEOIP=no
- DB=none OSSEC_TYPE=hybrid GEOIP=no
- DB=none OSSEC_TYPE=agent GEOIP=no
- DB=none OSSEC_TYPE=winagent GEOIP=no
- OSSEC_TYPE=test
- OSSEC_TYPE=server RULES=test
- OSSEC_TYPE=scan


compiler:
- gcc
- clang


matrix:
  fast_finish: true
  exclude:
    - compiler: clang
      env: DB=none OSSEC_TYPE=winagent GEOIP=no
    - compiler: clang
      env: OSSEC_TYPE=server RULES=test



before_script:
- sudo apt-get update -qq
- sudo apt-get install -y libevent-dev
- ( wget https://ftp.pcre.org/pub/pcre/pcre2-10.32.tar.gz
  && tar xzf pcre2-10.32.tar.gz -C src/external )
- if [[ "${GEOIP}" == "yes"  ]]; then ( sudo apt-get install geoip-bin geoip-database libgeoip-dev libgeoip1 ); fi
- if [[ "${PRELUDE}" == "yes" ]]; then ( sudo apt-get install libprelude-dev ); fi
- if [[ "${ZEROMQ}" == "yes" ]]; then ( sudo apt-get install libzmq3-dev libtool autoconf
  && wget https://github.com/zeromq/czmq/archive/v2.2.0.tar.gz
  && tar xfz v2.2.0.tar.gz && cd czmq-2.2.0/ && ./autogen.sh
  && ./configure && make all -j && sudo make install
  ); fi
- if [[ "${OSSEC_TYPE}" == "winagent" ]]; then ( sudo apt-get install aptitude && sudo aptitude -y install mingw-w64 nsis ); fi
- if [[ "${USE_SQLITE}" == "yes" ]]; then ( sudo apt-get install libsqlite3-dev sqlite3 ); fi
- if [[ "${USE_LIBSODIUM}" == "yes" ]]; then ( sudo add-apt-repository -y ppa:chris-lea/libsodium && sudo apt-get update
  && sudo apt-get install libsodium-dev libsodium13
  ); fi
- if [[ "${OSSEC_TYPE}" == "test" ]]; then ( sudo apt-get update && sudo apt-get install check valgrind ); fi
#- if [[ "${OSSEC_TYPE}" == "scan" ]]; then (  ); fi


script:
- COMMAND="V=1 TARGET=${OSSEC_TYPE}"
  && if ! [[ "${DB}" = "none" ]]; then COMMAND="${COMMAND} DATABASE=${DB}"; fi
  && if [[ "${GEOIP}" = "yes" ]]; then COMMAND="${COMMAND} USE_GEOIP=1"; fi
  && if [[ "${PRELUDE}" = "yes" ]]; then COMMAND="${COMMAND} USE_PRELUDE=1"; fi
  && if [[ "${ZEROMQ}" = "yes" ]]; then COMMAND="${COMMAND} USE_ZEROMQ=1"; fi
  && if [[ "${OSSEC_TYPE}" = "test" ]]; then COMMAND="${COMMAND} USE_PCRE2_JIT=0"; fi
  && ( cd src/
     && make --warn-undefined-variables ${COMMAND} settings
     && make --warn-undefined-variables ${COMMAND} external -j
     && make --warn-undefined-variables ${COMMAND} -j )
  && if ! [[ "${OSSEC_TYPE}" = "test" || "${OSSEC_TYPE}" = "winagent" ]]; then ( cd src/ && sudo make --warn-undefined-variables ${COMMAND} install ) fi

- if [[ "${OSSEC_TYPE}" == "test" ]]; then ( cd src/ && make --warn-undefined-variables test_valgrind ) fi
- if [[ "${RULES}" == "test" ]]; then ( cd src/ && sudo make V=1 TARGET=server test-rules ) fi
- if [[ "${OSSEC_TYPE}" == "scan" ]]; then ( git clone https://github.com/ddpbsd/ossec-scan.git ossec-scan && cd src/ && scan-build -o ../ossec-scan/scans/testing/server gmake TARGET=server USE_LIBSODIUM=y ) fi 


#after_success:
#  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then (cd _build/html/ && git config user.email travis-ci@travis && git config user.name  "Travis-CI" && git add . && git commit -m "deployed to github pages" && git push --force --quiet https://$GH_TOKEN@github.com/ossec/ossec.github.io.git); fi

